/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import DAO.ConnectionDB;
import com.itextpdf.text.Chunk;
import model.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BacSiDaKhoaForm extends javax.swing.JFrame {

    /**
     * Creates new form BacSiDaKhoa
     */
    Vector headerXetNghiem = new Vector();
    Vector dataXetNghiem = new Vector();

    Vector headerTimKiemHoSo = new Vector();
    Vector dataTimKiemHoSo = new Vector();

    Vector headerThuoc = new Vector();
    Vector dataThuoc = new Vector();
    ConnectionDB connect = new ConnectionDB();

    //luu tru nhung thuoc da them trong bang
    ArrayList<String> selectedXetNghiem = new ArrayList<>();
    ArrayList<String> selectedThuoc = new ArrayList<>();

    public BacSiDaKhoaForm() {
        initComponents();
        connect.connect();
        this.setLocationRelativeTo(null);

        //set up chuan doan ban dau
        Date ngaykham = new Date(System.currentTimeMillis());
        SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
        lbNgayKham.setText(dateformat.format(ngaykham));
        lbNgayKhamSauXN.setText(dateformat.format(ngaykham));

        //neu khong có bệnh nhân không cho thêm chuẩn đoán
        btnThemChuanDoan.setEnabled(false);
        btnThemChuanDoanSauXN.setEnabled(false);

        //them item vào trong combo box
        List<DichVu> danhSachXetNghiem = connect.danhSachDV();
        for (DichVu dichVu : danhSachXetNghiem) {
            cboxXetNghiem.addItem(dichVu.getTen());
        }

        thuoc = connect.danhSachThuoc();
        for (Thuoc t : thuoc) {
            cboxTenThuoc.addItem(t.getTenThuoc());
        }

        //tao table xet nghiem
        headerXetNghiem.add("Xét nghiệm");

        DefaultTableModel model = (DefaultTableModel) tblXetNghiem.getModel();
        model.setDataVector(dataXetNghiem, headerXetNghiem);

        //set up cho tab timKiemHoSO
        headerTimKiemHoSo.add("STT");
        headerTimKiemHoSo.add("Ngày khám");
        headerTimKiemHoSo.add("Chuẩn đoán trước xét nghiệm");
        headerTimKiemHoSo.add("Chuẩn đoán sau xét nghiệm");
        headerTimKiemHoSo.add("IDCT");
        
        DefaultTableModel modelTimKiem = (DefaultTableModel) tblLichSu.getModel();
        modelTimKiem.setDataVector(dataTimKiemHoSo, headerTimKiemHoSo);

        //setup cho tab SauXN
        headerThuoc.add("Tên thuốc");
        headerThuoc.add("Số lượng");
        DefaultTableModel modelThuoc = (DefaultTableModel) tblThuoc.getModel();
        modelThuoc.setDataVector(dataThuoc, headerThuoc);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TimHoSo = new javax.swing.JPanel();
        lbIDBenhNhan = new javax.swing.JLabel();
        txtIDBenhNhanTimKiem = new javax.swing.JTextField();
        btnTimKiemHoSo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        ChuanDoanBanDau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbNgayKham = new javax.swing.JLabel();
        btnTaoChuanDoan = new javax.swing.JButton();
        lbChuanDoanSoBo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChuanDoan = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cboxXetNghiem = new javax.swing.JComboBox<>();
        btnThemXetNghiem = new javax.swing.JButton();
        btnXoaxetNghiem = new javax.swing.JButton();
        btnThemChuanDoan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblXetNghiem = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaChuanDoan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbNgayKhamSauXN = new javax.swing.JLabel();
        btnTaoChuanDoanSauXN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaSauXN = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        cboxTenThuoc = new javax.swing.JComboBox<>();
        txtSoLuongThuoc = new javax.swing.JTextField();
        btnThemThuoc = new javax.swing.JButton();
        btnXoaThuoc = new javax.swing.JButton();
        btnThemChuanDoanSauXN = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblThuoc = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        lbIDBenhNhan.setText("ID bệnh nhân:");

        txtIDBenhNhanTimKiem.setToolTipText("");

        btnTimKiemHoSo.setBackground(new java.awt.Color(69, 155, 186));
        btnTimKiemHoSo.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiemHoSo.setText("Tìm kiếm");
        btnTimKiemHoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemHoSoActionPerformed(evt);
            }
        });

        jLabel4.setText("Lịch sử khám của bệnh nhân:");

        jLabel5.setText("Họ tên:");

        lbHoTen.setText("...");

        jLabel6.setText("Ngày sinh:");

        lbNgaySinh.setText("...");

        jLabel7.setText("Giới tính:");

        lbGioiTinh.setText("...");

        jLabel8.setText("SĐT:");

        lbSDT.setText("...");

        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Ngày khám", "Chuẩn đoán trước xét nghiệm", "Chuẩn đoán sau xét nghiệm", "IDCT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblLichSu);

        javax.swing.GroupLayout TimHoSoLayout = new javax.swing.GroupLayout(TimHoSo);
        TimHoSo.setLayout(TimHoSoLayout);
        TimHoSoLayout.setHorizontalGroup(
            TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimHoSoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TimHoSoLayout.createSequentialGroup()
                        .addComponent(lbIDBenhNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDBenhNhanTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiemHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(TimHoSoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(TimHoSoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimHoSoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TimHoSoLayout.createSequentialGroup()
                        .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TimHoSoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TimHoSoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TimHoSoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TimHoSoLayout.setVerticalGroup(
            TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimHoSoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDBenhNhan)
                    .addComponent(txtIDBenhNhanTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbHoTen))
                .addGap(18, 18, 18)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbNgaySinh))
                .addGap(31, 31, 31)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbGioiTinh))
                .addGap(27, 27, 27)
                .addGroup(TimHoSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbSDT))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Tìm hồ sơ", TimHoSo);

        jLabel1.setText("ID bệnh nhân:");

        jLabel2.setText("Ngày khám:");

        lbNgayKham.setText("...");

        btnTaoChuanDoan.setBackground(new java.awt.Color(69, 155, 186));
        btnTaoChuanDoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoChuanDoan.setText("Tạo chuẩn đoán");
        btnTaoChuanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoChuanDoanActionPerformed(evt);
            }
        });

        lbChuanDoanSoBo.setText("Chuẩn đoán sơ bộ:");

        txtAreaChuanDoan.setColumns(20);
        txtAreaChuanDoan.setRows(5);
        jScrollPane1.setViewportView(txtAreaChuanDoan);

        jLabel3.setText("Cần xét nghiệm thêm:");

        btnThemXetNghiem.setText("Thêm");
        btnThemXetNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXetNghiemActionPerformed(evt);
            }
        });

        btnXoaxetNghiem.setText("Xóa");
        btnXoaxetNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaxetNghiemActionPerformed(evt);
            }
        });

        btnThemChuanDoan.setBackground(new java.awt.Color(69, 155, 186));
        btnThemChuanDoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThemChuanDoan.setText("Thêm chuẩn đoán");
        btnThemChuanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChuanDoanActionPerformed(evt);
            }
        });

        tblXetNghiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Xét nghiệm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblXetNghiem);

        javax.swing.GroupLayout ChuanDoanBanDauLayout = new javax.swing.GroupLayout(ChuanDoanBanDau);
        ChuanDoanBanDau.setLayout(ChuanDoanBanDauLayout);
        ChuanDoanBanDauLayout.setHorizontalGroup(
            ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                                .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbChuanDoanSoBo)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTaoChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                        .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ChuanDoanBanDauLayout.createSequentialGroup()
                                        .addComponent(btnThemXetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoaxetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnThemChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cboxXetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        ChuanDoanBanDauLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThemXetNghiem, btnXoaxetNghiem});

        ChuanDoanBanDauLayout.setVerticalGroup(
            ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lbNgayKham)
                    .addComponent(btnTaoChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lbChuanDoanSoBo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                        .addComponent(cboxXetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(ChuanDoanBanDauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaxetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemXetNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnThemChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(ChuanDoanBanDauLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        ChuanDoanBanDauLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThemXetNghiem, btnXoaxetNghiem});

        jTabbedPane1.addTab("Chuẩn đoán ban đầu", ChuanDoanBanDau);

        jLabel10.setText("Mã chuẩn đoán:");

        txtMaChuanDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaChuanDoanActionPerformed(evt);
            }
        });

        jLabel11.setText("Ngày khám:");

        lbNgayKhamSauXN.setText("..");

        btnTaoChuanDoanSauXN.setBackground(new java.awt.Color(69, 155, 186));
        btnTaoChuanDoanSauXN.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoChuanDoanSauXN.setText("Tạo chuẩn đoán");
        btnTaoChuanDoanSauXN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoChuanDoanSauXNActionPerformed(evt);
            }
        });

        jLabel12.setText("Chuẩn đoán sau XN:");

        txtAreaSauXN.setColumns(20);
        txtAreaSauXN.setRows(5);
        jScrollPane4.setViewportView(txtAreaSauXN);

        jLabel13.setText("Thuốc cần mua:");

        cboxTenThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTenThuocActionPerformed(evt);
            }
        });

        btnThemThuoc.setText("Thêm");
        btnThemThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocActionPerformed(evt);
            }
        });

        btnXoaThuoc.setText("Xóa");
        btnXoaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuocActionPerformed(evt);
            }
        });

        btnThemChuanDoanSauXN.setBackground(new java.awt.Color(69, 155, 186));
        btnThemChuanDoanSauXN.setForeground(new java.awt.Color(255, 255, 255));
        btnThemChuanDoanSauXN.setText("Thêm chuẩn đoán/ In phiếu");
        btnThemChuanDoanSauXN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChuanDoanSauXNActionPerformed(evt);
            }
        });

        tblThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên thuốc", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblThuoc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbNgayKhamSauXN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTaoChuanDoanSauXN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemChuanDoanSauXN, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(cboxTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoLuongThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnXoaThuoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThemThuoc, btnXoaThuoc});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaChuanDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lbNgayKhamSauXN)
                    .addComponent(btnTaoChuanDoanSauXN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuongThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(btnXoaThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(btnThemChuanDoanSauXN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThemThuoc, btnXoaThuoc});

        jTabbedPane1.addTab("Chuẩn đoán sau XN", jPanel1);

        jLabel9.setBackground(new java.awt.Color(69, 155, 186));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PHÒNG KHÁM ĐA KHOA QUANG TRUNG");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnThemChuanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChuanDoanActionPerformed
        ChiTietKhamBenh chitiet = new ChiTietKhamBenh();
        chitiet.setIDBN(Integer.parseInt(txtIDBenhNhan.getText()));
        chitiet.setChuanDoanBanDau(txtAreaChuanDoan.getText());
        chitiet.setNgayKham(new java.sql.Date(System.currentTimeMillis()));

        List<String> xetnghiem = new ArrayList<>();
        for (Iterator it = dataXetNghiem.iterator(); it.hasNext();) {
            Vector object = (Vector) it.next();
            xetnghiem.add((String) object.get(0));
        }
        
        if(txtAreaChuanDoan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Không được để trống chuẩn đoán!!", "Thông báo", 0);
            return;
        }
        
        connect.themChuanDoan(chitiet, xetnghiem,Integer.parseInt(txtIDBenhNhan.getText()));
        

        //xoa du lieu trong mang xet nghiem da chon
        selectedXetNghiem.clear();
        btnThemChuanDoan.setEnabled(false);
        btnXoaxetNghiem.setEnabled(false);
        btnThemXetNghiem.setEnabled(false);
        txtIDBenhNhan.setEnabled(true);
    }//GEN-LAST:event_btnThemChuanDoanActionPerformed

    private void btnXoaxetNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaxetNghiemActionPerformed
        int selected = tblXetNghiem.getSelectedRow();
        if (selected < 0 || selected >= dataXetNghiem.size()) {
            JOptionPane.showMessageDialog(null, "Chọn một bản ghi trong bảng!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedXetNghiem.remove(selected);
            dataXetNghiem.remove(selected);
            tblXetNghiem.updateUI();
        }
    }//GEN-LAST:event_btnXoaxetNghiemActionPerformed

    private void btnThemXetNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXetNghiemActionPerformed
        Vector row = new Vector();

        if (!selectedXetNghiem.contains(cboxXetNghiem.getSelectedItem().toString())) {
            row.add(cboxXetNghiem.getSelectedItem().toString());
            selectedXetNghiem.add(cboxXetNghiem.getSelectedItem().toString());
            dataXetNghiem.add(row);
        } else {
            JOptionPane.showMessageDialog(null, "Đã có trong danh sách.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        tblXetNghiem.updateUI();
    }//GEN-LAST:event_btnThemXetNghiemActionPerformed

    private void btnTaoChuanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoChuanDoanActionPerformed
        //tao chuan doan

        try {
            int idbn = Integer.parseInt(txtIDBenhNhan.getText());
            if (idbn > 0) {
                BenhNhan bn = connect.timBenhNhan(idbn);
                if (bn != null) {
                    JOptionPane.showMessageDialog(null, "Hãy nhập chuẩn đoán và các xét nghiệm(nếu có).", "Thông báo.", JOptionPane.INFORMATION_MESSAGE);
                    txtAreaChuanDoan.setText("");
                    txtIDBenhNhan.setEnabled(false);
                    dataXetNghiem.clear();
                    selectedXetNghiem.clear();
                    tblXetNghiem.updateUI();
                    btnThemChuanDoan.setEnabled(true);
                    btnXoaxetNghiem.setEnabled(true);
                    btnThemXetNghiem.setEnabled(true);
                    lbNgayKham.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy bênh nhân.", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nhập id lớn hơn 0!!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnTaoChuanDoanActionPerformed

    private void btnTimKiemHoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemHoSoActionPerformed
        try {
            int idbn = Integer.parseInt(txtIDBenhNhanTimKiem.getText());
            if (idbn > 0) {
                BenhNhan bn = connect.timBenhNhan(idbn);
                if (bn != null) {
                    lbHoTen.setText(bn.getTen());
                    lbGioiTinh.setText(bn.getGioiTinh());
                    lbNgaySinh.setText(new SimpleDateFormat("dd/MM/yyyy").format(bn.getNgaySinh()));
                    lbSDT.setText(bn.getSDT());

                    //Nếu tìm thấy bênh nhân mới tìm lịch sử khám
                    List<ChiTietKhamBenh> lichSuKham = connect.timKiemHoSo(idbn);
                    dataTimKiemHoSo.clear();
                    if (!lichSuKham.isEmpty()) {
                        int count = 1;
                        for (ChiTietKhamBenh chitiet : lichSuKham) {
                            Vector row = new Vector();
                            row.add(count);
                            row.add(new SimpleDateFormat("dd/MM/yyyy").format(chitiet.getNgayKham()));
                            row.add(chitiet.getChuanDoanBanDau());
                            row.add(chitiet.getChuanDoanSauXetNghiem());
                            row.add(chitiet.getIDCT());
                            dataTimKiemHoSo.add(row);
                            count++;
                        }
                        tblLichSu.updateUI();
                    } else {
                        JOptionPane.showMessageDialog(null, "Không tìm thấy lịch sử khám.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        dataTimKiemHoSo.clear();
                        tblLichSu.updateUI();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy bệnh nhân trong cơ sở dữ liệu!", "WARNING", JOptionPane.WARNING_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(null, "Nhập id lớn hơn 0!!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "IDBN không hợp lệ! Xin thử lại!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemHoSoActionPerformed

    //Cac ham sau XetNghiem

    private void btnTaoChuanDoanSauXNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoChuanDoanSauXNActionPerformed
        try {
            int idct = Integer.parseInt(txtMaChuanDoan.getText());
            if (idct > 0) {
                if (connect.timChiTietKham(idct)) {
                    JOptionPane.showMessageDialog(null, "Hãy nhập chuẩn đoán và các thuốc cần kê đơn.", "Thông báo.", JOptionPane.INFORMATION_MESSAGE);
                    txtAreaSauXN.setText("");
                    btnThemChuanDoanSauXN.setEnabled(true);
                    txtSoLuongThuoc.setText("");
                    lbNgayKhamSauXN.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));

                } else {
                    JOptionPane.showMessageDialog(null, "Không có trong cơ sở dữ liệu.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nhập sai cú pháp mã chuẩn đoán. Xin thử lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập id lớn hơn 0!!!", "Thông báo.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTaoChuanDoanSauXNActionPerformed

    private void btnThemThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocActionPerformed

        Vector row = new Vector();
        try {
            int soluong = Integer.parseInt(txtSoLuongThuoc.getText());
            if (soluong > 0) {
                if (!selectedThuoc.contains(cboxTenThuoc.getSelectedItem().toString())) {
                    Thuoc t = thuoc.get(cboxTenThuoc.getSelectedIndex());
                    t.setSoLuong(soluong);
                    thuocCanMua.add(t);
                    row.add(cboxTenThuoc.getSelectedItem().toString());
                    row.add(txtSoLuongThuoc.getText());
                    selectedThuoc.add(cboxTenThuoc.getSelectedItem().toString());
                    dataThuoc.add(row);
                } else {
                    JOptionPane.showMessageDialog(null, "Đã có trong danh sách.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
                tblThuoc.updateUI();
            } else {
                JOptionPane.showMessageDialog(null, "Nhập đúng số lượng thuốc!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập đúng số lượng thuốc!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnThemThuocActionPerformed

    private void btnXoaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuocActionPerformed
        int selected = tblThuoc.getSelectedRow();
        if (selected < 0 || selected >= dataThuoc.size()) {
            JOptionPane.showMessageDialog(null, "Chọn một bản ghi trong bảng!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            thuocCanMua.remove(selected);
            selectedThuoc.remove(selected);
            dataThuoc.remove(selected);
            tblThuoc.updateUI();
        }
    }//GEN-LAST:event_btnXoaThuocActionPerformed

    private void btnThemChuanDoanSauXNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChuanDoanSauXNActionPerformed
        try {
            String chuanDoanSauXN = txtAreaSauXN.getText();
            int idct = Integer.parseInt(txtMaChuanDoan.getText());
            boolean themThuocKeDon;
            boolean add = connect.themChuanDoanSauXN(chuanDoanSauXN, idct);
            connect.themChiTietThuoc(idct, thuocCanMua);
            BenhNhan bn = (BenhNhan) connect.getTTInPhieu(idct, null, null).get(0);
            if (add) {
                JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Không thêm được chuẩn đoán sau xét nghiệm. Xin thử lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
            // font viet tieng viet
            // font arial dam
            String path = "Unicode\\arialbd.ttf";
            FontFactory.register(path);
            Font arialb = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
            // font arial binh thuong
            path = "Unicode\\arial.ttf";
            FontFactory.register(path);
            Font arial = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
            // font arial nghieng
            path = "Unicode\\ariali.ttf";
            FontFactory.register(path);
            Font ariali = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));

            String locate = "";

            JFileChooser j = new JFileChooser();
            j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Integer opt = j.showSaveDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION) {
                locate = j.getSelectedFile().getPath();
            }

            // tao file pdf
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document,
                    new FileOutputStream(locate + "\\Don-thuoc.pdf"));
            writer.setPdfVersion(PdfWriter.PDF_VERSION_1_7);
            document.open();
            // phan dau
            Paragraph p = new Paragraph();
            Chunk c = new Chunk("PHÒNG KHÁM ĐA KHOA QUANG TRUNG");
            arialb.setSize(12);
            c.setFont(arialb);
            p.add(c);
            document.add(p);

            c = new Chunk("Địa chỉ: Số 1, Đại Cồ Việt, Hai Bà Trưng, Hà Nội");
            arialb.setSize(12);
            c.setFont(arialb);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            long time = System.currentTimeMillis();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String ngay = format.format(time);
            c = new Chunk("Ngày: " + ngay);
            c.setFont(arialb);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            // tittle
            c = new Chunk("PHIẾU KẾT QUẢ");
            arialb.setSize(18);
            c.setFont(arialb);
            p = new Paragraph();
            p.add(c);
            p.setAlignment(Element.ALIGN_CENTER);
            p.setSpacingAfter(20);
            p.setSpacingBefore(30);
            document.add(p);

            // thong tin benh nhan
            c = new Chunk("Mã chuẩn đoán: " + idct);
            arial.setSize(10);
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Họ tên: " + bn.getTen());
            arial.setSize(10);
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Giới tính: " + bn.getGioiTinh());
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Ngày sinh: " + bn.getNgaySinh());
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Địa chỉ: " + bn.getDiaChi());
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Số điện thoại: " + bn.getSDT());
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            document.add(p);

            c = new Chunk("Chứng minh thư: " + bn.getCMT());
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            p.setSpacingAfter(20);
            document.add(p);

            p = new Paragraph(new Chunk("Kết quả", arial));
            p.setFont(arial);
            p.setSpacingAfter(15);
            document.add(p);
            PdfPTable tb = new PdfPTable(1);
            PdfPCell cell;
            c = new Chunk(txtAreaSauXN.getText());
            c.setFont(arial);
            p = new Paragraph(c);
            cell = new PdfPCell(p);
            cell.setPaddingBottom(15);
            cell.setPaddingTop(10);
            tb.addCell(cell);
            tb.setSpacingAfter(20);
            document.add(tb);

            p = new Paragraph(new Chunk("Đơn thuốc", arial));
            p.setFont(arial);
            document.add(p);
            tb = new PdfPTable(2);
            c = new Chunk("Tên thuốc");
            c.setFont(arial);
            p = new Paragraph(c);
            cell = new PdfPCell(p);
            cell.setPaddingBottom(15);
            cell.setPaddingTop(10);
            tb.addCell(cell);
            c = new Chunk("Số lượng");
            c.setFont(arial);
            p = new Paragraph(c);
            cell = new PdfPCell(p);
            cell.setPaddingBottom(15);
            cell.setPaddingTop(10);
            tb.addCell(cell);
            for (Thuoc t : thuocCanMua) {
                c = new Chunk(t.getTenThuoc());
                c.setFont(arial);
                p = new Paragraph(c);
                cell = new PdfPCell(p);
                cell.setPaddingBottom(15);
                cell.setPaddingTop(10);
                tb.addCell(cell);
                c = new Chunk(t.getSoLuong() + "");
                c.setFont(arial);
                p = new Paragraph(c);
                cell = new PdfPCell(p);
                cell.setPaddingBottom(15);
                cell.setPaddingTop(10);
                tb.addCell(cell);
            }
            tb.setSpacingBefore(15);
            document.add(tb);
            //chu ky
            c = new Chunk("Bác sĩ đa khoa:...........................................");
            c.setFont(arial);
            p = new Paragraph();
            p.add(c);
            p.setSpacingBefore(20);
            p.setAlignment(Element.ALIGN_RIGHT);
            document.add(p);

            // ket thuc ghi
            document.close();
            writer.close();
        } catch (DocumentException ex) {
            Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemChuanDoanSauXNActionPerformed

    private void txtMaChuanDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaChuanDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaChuanDoanActionPerformed

    private void cboxTenThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTenThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTenThuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BacSiDaKhoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BacSiDaKhoaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChuanDoanBanDau;
    private javax.swing.JPanel TimHoSo;
    private javax.swing.JButton btnTaoChuanDoan;
    private javax.swing.JButton btnTaoChuanDoanSauXN;
    private javax.swing.JButton btnThemChuanDoan;
    private javax.swing.JButton btnThemChuanDoanSauXN;
    private javax.swing.JButton btnThemThuoc;
    private javax.swing.JButton btnThemXetNghiem;
    private javax.swing.JButton btnTimKiemHoSo;
    private javax.swing.JButton btnXoaThuoc;
    private javax.swing.JButton btnXoaxetNghiem;
    private javax.swing.JComboBox<String> cboxTenThuoc;
    private javax.swing.JComboBox<String> cboxXetNghiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbChuanDoanSoBo;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbIDBenhNhan;
    private javax.swing.JLabel lbNgayKham;
    private javax.swing.JLabel lbNgayKhamSauXN;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JTable tblLichSu;
    private javax.swing.JTable tblThuoc;
    private javax.swing.JTable tblXetNghiem;
    private javax.swing.JTextArea txtAreaChuanDoan;
    private javax.swing.JTextArea txtAreaSauXN;
    private javax.swing.JTextField txtIDBenhNhan;
    private javax.swing.JTextField txtIDBenhNhanTimKiem;
    private javax.swing.JTextField txtMaChuanDoan;
    private javax.swing.JTextField txtSoLuongThuoc;
    // End of variables declaration//GEN-END:variables
    private List<Thuoc> thuocCanMua = new ArrayList<>();
    private List<Thuoc> thuoc;
}
