/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import DAO.ConnectionDB;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.BenhNhan;

/**
 *
 * @author dell
 */
public class LeTanForm extends javax.swing.JFrame {

    /**
     * Creates new form LeTan
     */
    public LeTanForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtCmt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel9.setBackground(new java.awt.Color(69, 155, 186));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PHÒNG KHÁM ĐA KHOA QUANG TRUNG");
        jLabel9.setOpaque(true);

        jLabel4.setText("Thông tin bệnh nhân");

        jLabel1.setText("Họ tên:");

        jLabel2.setText("Giới tính:");

        jLabel3.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ:");

        jLabel6.setText("SĐT liên hệ:");

        jLabel7.setText("Số CMT:");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        txtCmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(69, 155, 186));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ThêmTT/In phiếu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCmt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)))
                .addContainerGap(245, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel2))
                                                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(txtCmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Thông tin bệnh nhân");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCmtActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            ConnectionDB db = new ConnectionDB();
            db.connect();
            //bệnh nhân mới
            BenhNhan bnmoi = new BenhNhan();
            bnmoi.setTen(txtHoTen.getText());
            bnmoi.setGioiTinh(txtGioiTinh.getText());
            Date date = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgaySinh.getText()).getTime());
            bnmoi.setNgaySinh(date);
            bnmoi.setDiaChi(txtDiaChi.getText());
            bnmoi.setSDT(txtSdt.getText());
            bnmoi.setCMT(txtCmt.getText());
            BenhNhan bncu = new BenhNhan();
            bncu = db.themBenhNhan(bnmoi.getTen(), bnmoi.getGioiTinh(), bnmoi.getNgaySinh(), bnmoi.getDiaChi(), bnmoi.getSDT(), bnmoi.getCMT());
            if (bncu == null) {
                int id = db.getLastID();
                bnmoi.setID(id);
                inPhieu(bnmoi);
                //in phiếu với các thông tin đã nhập của bnmoi
            } else {
                //in phiếu với các thông tin của bncu
                if (bnmoi.getTen().equals(bncu.getTen()) && bnmoi.getGioiTinh().equals(bncu.getGioiTinh())
                        && bnmoi.getDiaChi().equals(bncu.getDiaChi()) && bnmoi.getSDT().equals(bncu.getSDT())
                        && bnmoi.getNgaySinh().getTime() == bncu.getNgaySinh().getTime()
                        ) {
                    JOptionPane.showMessageDialog(null, "Bệnh nhân đã tồn tại!! Chỉ in phiếu thứ tự!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    inPhieu(bncu);
                }else{
                    JOptionPane.showMessageDialog(null, "Số chứng minh thư đã được sử dụng!", "Thông báo", 2);
                    STT--;
                }

            }
            STT++;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại ngày nhập!!!", "thông báo", 0);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeTanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeTanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeTanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeTanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeTanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCmt;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
    private static int STT = 1;

    //ham bo sung
    public void inPhieu(BenhNhan bn) throws Exception {
        // font viet tieng viet
        // font arial dam
        String path = "Unicode\\arialbd.ttf";
        FontFactory.register(path);
        Font arialb = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
        // font arial binh thuong
        path = "Unicode\\arial.ttf";
        FontFactory.register(path);
        Font arial = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
        // font arial nghieng
        path = "Unicode\\ariali.ttf";
        FontFactory.register(path);
        Font ariali = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));

        String locate="";
        
        JFileChooser j= new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Integer opt = j.showSaveDialog(this);
        if(opt==JFileChooser.APPROVE_OPTION){
            locate=j.getSelectedFile().getPath();
        }
        
        // tao file pdf
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document,
                new FileOutputStream(locate+"\\Phieu-thu-tu.pdf"));
        writer.setPdfVersion(PdfWriter.PDF_VERSION_1_7);
        document.open();
        // phan dau
        Paragraph p = new Paragraph();
        Chunk c = new Chunk("PHÒNG KHÁM ĐA KHOA QUANG TRUNG");
        arialb.setSize(12);
        c.setFont(arialb);
        p.add(c);
        document.add(p);

        c = new Chunk("Địa chỉ: Số 1, Đại Cồ Việt, Hai Bà Trưng, Hà Nội");
        arialb.setSize(12);
        c.setFont(arialb);
        p = new Paragraph();
        p.add(c);
        document.add(p);

        long time = System.currentTimeMillis();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String ngay = format.format(time);
        c = new Chunk("Ngày: " + ngay);
        c.setFont(arialb);
        p = new Paragraph();
        p.add(c);
        document.add(p);

        // tittle
        c = new Chunk("PHIẾU THỨ TỰ");
        arialb.setSize(20);
        c.setFont(arialb);
        p = new Paragraph();
        p.add(c);
        p.setAlignment(Element.ALIGN_CENTER);
        p.setSpacingAfter(20);
        p.setSpacingBefore(30);
        document.add(p);

        // thong tin benh nhan
        c = new Chunk("Số thứ tự khám: " + STT);
        arialb.setSize(12);
        c.setFont(arialb);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Họ tên: " + bn.getTen());
        arial.setSize(12);
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Giới tính: " + bn.getGioiTinh());
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Ngày sinh: " + bn.getNgaySinh());
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Địa chỉ: " + bn.getDiaChi());
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Số điện thoại: " + bn.getSDT());
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        document.add(p);

        c = new Chunk("Chứng minh thư: " + bn.getCMT());
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setSpacingAfter(6);
        p.setSpacingAfter(20);
        document.add(p);

        //
        c = new Chunk("Lễ tân:...........................................");
        c.setFont(arial);
        p = new Paragraph();
        p.add(c);
        p.setAlignment(Element.ALIGN_RIGHT);
        document.add(p);

        // ket thuc ghi
        document.close();
        writer.close();
        JOptionPane.showMessageDialog(null, "In thành công. Mã bệnh nhân: "+bn.getID(),"Thông báo", 0);
    }

}
