/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import com.itextpdf.text.*;
import model.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import DAO.ConnectionDB;
import com.itextpdf.text.pdf.BaseFont;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manhpp
 */
public class ThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form DuocSi
     */
    public ThanhToan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setTitle("Thanh toán");

        jLabel1.setText("Mã chuẩn đoán");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(69, 155, 186));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PHÒNG KHÁM ĐA KHOA QUANG TRUNG");
        jLabel2.setOpaque(true);

        jLabel3.setText("Ngày Khám");

        jLabel4.setText("Các dịch vụ đã dùng");

        jLabel5.setText("Các thuốc cần mua");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Tổng tiền");

        jButton1.setBackground(new java.awt.Color(69, 155, 186));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thanh Toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(69, 155, 186));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tìm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Giá"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên thuốc", "Số lượng (viên)", "Đơn giá (VND/Viên)", "Tình trạng"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConnectionDB db = new ConnectionDB();
        db.connect();

        Document file = new Document();

        //cap nhat so luong thuoc
        if (jTextField1.getText().isEmpty()); else {
            int idct = Integer.parseInt(jTextField1.getText());

            ChiTietKhamBenh ct = db.timCT(idct);

            ArrayList<Thuoc> dsThuoc = db.dsThuoc(idct);
            if (dsThuoc == null) {
                JOptionPane.showMessageDialog(null, "Khong tim thay thuoc nao!");
            } else {

                try {
                    // font viet tieng viet
                    // font arial dam
                    String path = "Unicode\\arialbd.ttf";
                    FontFactory.register(path);
                    Font bold = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                    // font arial binh thuong
                    path = "Unicode\\arial.ttf";
                    FontFactory.register(path);
                    Font arial = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
                    // font arial nghieng
                    path = "Unicode\\ariali.ttf";
                    FontFactory.register(path);
                    Font italic = new Font(BaseFont.createFont(path, BaseFont.IDENTITY_H, BaseFont.EMBEDDED));

                    String nameFile = "don_" + idct + ".pdf";
                    PdfWriter.getInstance(file, new FileOutputStream(nameFile));
                    file.open();
//                    Font bold = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
//                    Font italic = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.ITALIC);
                    Paragraph pr1 = new Paragraph("PHÒNG KHÁM ĐA KHOA QUANG TRUNG", bold);
                    Paragraph pr2 = new Paragraph("Phiếu Thu Phí Khám Bệnh",arial);
                    pr1.setAlignment(Element.ALIGN_CENTER);
                    pr1.setSpacingAfter(20);
                    pr2.setAlignment(Element.ALIGN_CENTER);
                    pr2.setSpacingAfter(20);
                    Paragraph pr3 = new Paragraph("                 Tên người mua: " + db.timTen(idct) + "                                                                                ID: " + idct,arial);
                    pr3.setSpacingAfter(20);
                    file.add(pr1);
                    file.add(pr2);
                    file.add(pr3);

                    Paragraph pr4 = new Paragraph("                 1. Phí dịch vụ: ", italic);
                    pr4.setSpacingAfter(15);
                    file.add(pr4);

                    PdfPTable table = new PdfPTable(2);

                    PdfPCell header1 = new PdfPCell(new Paragraph("                     Tên dịch vụ", arial));
                    header1.setPadding(5);
                    PdfPCell header2 = new PdfPCell(new Paragraph("                     Giá dịch vụ", arial));
                    header2.setPadding(5);
                    table.addCell(header1);
                    table.addCell(header2);

                    PdfPCell cell;
                    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();

                    for (int i = 0; i < model1.getRowCount(); i++) {
                        for (int j = 0; j < model1.getColumnCount(); j++) {
                            cell = new PdfPCell(new Paragraph(model1.getValueAt(i, j).toString(),arial));
                            cell.setPadding(5);
                            table.addCell(cell);
                        }
                    }

                    file.add(table);

                    Paragraph pr5 = new Paragraph("                 2. Phí mua thuốc: ", italic);
                    pr5.setSpacingBefore(15);
                    pr5.setSpacingAfter(15);

                    file.add(pr5);

                    table = new PdfPTable(4);

                    header1 = new PdfPCell(new Paragraph("Tên thuốc"));
                    header1.setPadding(5);
                    header2 = new PdfPCell(new Paragraph("Số lượng", arial));
                    header2.setPadding(5);
                    PdfPCell header3 = new PdfPCell(new Paragraph("Đơn giá",arial));
                    header3.setPadding(5);
                    PdfPCell header4 = new PdfPCell(new Paragraph("Thành tiền", arial));
                    header4.setPadding(5);
                    table.addCell(header1);
                    table.addCell(header2);
                    table.addCell(header3);
                    table.addCell(header4);

                    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

                    for (int i = 0; i < model2.getRowCount(); i++) {
                        for (int j = 0; j < model2.getColumnCount() - 1; j++) {
                            cell = new PdfPCell(new Paragraph(model2.getValueAt(i, j).toString(), arial));
                            cell.setPadding(5);
                            table.addCell(cell);
                        }

                        cell = new PdfPCell(new Paragraph(Integer.toString((Integer.parseInt(model2.getValueAt(i, 2).toString()) * Integer.parseInt(model2.getValueAt(i, 1).toString()))),arial));
                        table.addCell(cell);
                    }

                    file.add(table);

                    bold.setSize(14);
                    Paragraph pr6 = new Paragraph("                 Tổng tiền: " + jTextField3.getText()+" VND", bold);
                    pr6.setSpacingBefore(15);
                    pr6.setSpacingAfter(15);
                    file.add(pr6);

                    DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss                   ");

                    Date today = new Date(System.currentTimeMillis());
                    String reportDate = df.format(today);
                    Paragraph pr7 = new Paragraph(reportDate);
                    pr7.setAlignment(Element.ALIGN_RIGHT);
                    pr7.setSpacingAfter(15);
                    file.add(pr7);

                    Paragraph pr8 = new Paragraph("                 Chứ ký người mua:                                                                     Chữ ký dược sĩ",arial);
                    file.add(pr8);

                    file.close();
                } catch (DocumentException e) {
                    e.printStackTrace();
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException ex) {
                    Logger.getLogger(ThanhToan.class.getName()).log(Level.SEVERE, null, ex);
                }

                for (int i = 0; i < dsThuoc.size(); i++) {
                    if (dsThuoc.get(i).getSoLuongConLai() >= dsThuoc.get(i).getSoLuong()) {
                        db.updateThuoc(dsThuoc.get(i).getId(), dsThuoc.get(i).getSoLuongConLai() - dsThuoc.get(i).getSoLuong());
                    }
                }
                JOptionPane.showMessageDialog(null, "Thành công!!!", "Thông báo", 1);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ConnectionDB db = new ConnectionDB();
        db.connect();

        //hien thong tin len bang dich vuva bang thuoc
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống id", "Thông báo", 0);
        } else {
            int idct = Integer.parseInt(jTextField1.getText());
            int tongTien = 0;

            ChiTietKhamBenh ct = db.timCT(idct);
            if (ct == null) {
                JOptionPane.showMessageDialog(null, "Không tồn tại chi tiết khám bệnh này!!!", "Thông báo", 0);
            }
            Date ngayKham = ct.getNgayKham();
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
            String text = df.format(ngayKham);
            jTextField5.setText(text);

            ArrayList<DichVu> dsdv = db.dsDichVu(idct);
//            System.out.println(dsdv.size());
            if (dsdv == null) {
                JOptionPane.showMessageDialog(null, "Khong tim thay dich vu nao!");
            } else {
                DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
                model1.setRowCount(0);

                Object[] col = new Object[2];

                for (int i = 0; i < dsdv.size(); i++) {
                    col[0] = dsdv.get(i).getTen();
                    col[1] = dsdv.get(i).getGia();
                    model1.addRow(col);
                    tongTien += dsdv.get(i).getGia();
                }
            }

            ArrayList<Thuoc> dsThuoc = db.dsThuoc(idct);
            if (dsThuoc == null) {
                JOptionPane.showMessageDialog(null, "Khong tim thay thuoc nao!");
            } else {

                DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
                model2.setRowCount(0);

                Object[] col = new Object[4];

                for (int i = 0; i < dsThuoc.size(); i++) {
                    col[0] = dsThuoc.get(i).getTenThuoc();
                    col[1] = dsThuoc.get(i).getSoLuong();
                    col[2] = dsThuoc.get(i).getDonGia();
                    if (dsThuoc.get(i).getSoLuongConLai() >= dsThuoc.get(i).getSoLuong()) {
                        col[3] = "ok";
                        tongTien += dsThuoc.get(i).getSoLuong() * dsThuoc.get(i).getDonGia();
                    } else {
                        col[3] = "khong du thuoc";
                    }

                    model2.addRow(col);
                }
            }

            jTextField3.setText(String.valueOf(tongTien));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
